print("Hello World")
#print("Hello Again")
print("I like typing this.")
print("Okay this seems fair.")
print('Yay! Underscored.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
